name: rpgnotes
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ffmpeg
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # Matches the version from your logs
  - numpy
  - pydub
  - transformers
  - matplotlib
  - safetensors
  - ipykernel
  - pip:
    - audiostretchy
    - more-itertools
    - openai-whisper
    - tiktoken
    - soundfile
    - librosa 